baseURL = 'https://allthingscode.github.io/articles/'
languageCode = 'en'
title = 'All Things Code - Articles'
theme = 'PaperMod'

[params]
  defaultTheme = "dark"
  disableThemeToggle = false
  disableSpecial1stPost = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true

  [params.articleSignature]
    tagline = "The Pragmatic Agentic Solutions Architect (Matthew Hayes)"

[author]
  name = "Matthew Hayes"
  linkedin = "https://www.linkedin.com/in/matthew-l-hayes/"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
